### ISSUE TITLE
Display Recall Product Information

### ISSUE THREAD

**Issue by mtross-kpmg** [jardilio-kpmg/ads-rfq-prototype#5]
As a consumer user, I want to see details on a recalled product to determine if it impacts my area.

Acceptance Criteria:
1. Display product description
2. Display reason for recall
3. Display recalling firm
4. Display recall initiation date
5. Display status
6. Display distribution pattern
7. Display code info
8. Display classification

**Comment by jardilio-kpmg** [comment]
![image](https://cloud.githubusercontent.com/assets/12973322/8312359/0f102962-19aa-11e5-8bbd-071792fc8241.png)

**Comment by jvillarreal-kpmg** [comment]
This is completed with the following observations:

1 Footer was not added because:
a New search is already part of the top menu
b Add to list would be added in top menu if time permitted
c Chart would be added to top menu

2 Active Recalls and Past recalls are assuming their count is based on the sum of recalls of a product with the selected product UPC exact number. 

3 Image was not added because service doesn't provide that information. It would need third party service to get images.
